# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":name"
    replace: "Felix Tröbinger"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo -n Hello from your shell"

  - trigger: ":angery"
    image_path: "/home/felix/Pictures/memes/angery.jpg"

  - trigger: ":pikachu"
    image_path: "/home/felix/Pictures/memes/pikachu.jpg"

  - trigger: ":god"
    image_path: "/home/felix/Pictures/memes/god.jpg"

  - trigger: ":confused"
    image_path: "/home/felix/Pictures/memes/confused_krabs.jpg"

  - trigger: ":angry"
    image_path: "/home/felix/Pictures/memes/angry.jpg"

  - trigger: ":comeagain"
    image_path: "/home/felix/Pictures/memes/come_again.jpg"

  - trigger: ":awkward"
    image_path: "/home/felix/Pictures/memes/awkward.jpg"

  - trigger: ":hackerman"
    image_path: "/home/felix/Pictures/memes/hackerman.jpg"
  - trigger: ":ytho"
    image_path: "/home/felix/Pictures/memes/ytho.jpg"
  - trigger: ":nice"
    image_path: "/home/felix/Pictures/memes/nice.png"
  - trigger: ":breckfast"
    image_path: "/home/felix/Pictures/memes/breckfast.jpg"
  - trigger: ":what"
    image_path: "/home/felix/Pictures/memes/what.png"
