# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

enable_passive: true
passive_key: CTRL

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":name"
    replace: "Felix Tröbinger"

  - trigger: ":serverip"
    replace: "37.252.191.46"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo -n Hello from your shell"

  - trigger: ":rev"
    replace: "{{output}}"
    passive_only: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $0 | rev"
          trim: true

  - trigger: ":sponge"
    replace: "{{output}}"
    passive_only: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $0 | spunge"
          trim: true

  - trigger: ":greet"
    replace: "Hey $0$, how are you?\nIt's been a while!"
    passive_only: true

  - trigger: ":ayylmao"
    replace: "https://www.youtube.com/watch?v=kiEqGhgWf5Y"

  - trigger: ":rickroll"
    replace: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  - trigger: ":angery"
    image_path: "/home/felix/Pictures/memes/angery.jpg"

  - trigger: ":pikachu"
    image_path: "/home/felix/Pictures/memes/pikachu.jpg"

  - trigger: ":god"
    image_path: "/home/felix/Pictures/memes/god.jpg"

  - trigger: ":confused"
    image_path: "/home/felix/Pictures/memes/confused_krabs.jpg"

  - trigger: ":angry"
    image_path: "/home/felix/Pictures/memes/angry.jpg"

  - trigger: ":comeagain"
    image_path: "/home/felix/Pictures/memes/come_again.jpg"

  - trigger: ":awkward"
    image_path: "/home/felix/Pictures/memes/awkward.jpg"

  - trigger: ":hackerman"
    image_path: "/home/felix/Pictures/memes/hackerman.jpg"

  - trigger: ":ytho"
    image_path: "/home/felix/Pictures/memes/ytho.jpg"

  - trigger: ":nice"
    image_path: "/home/felix/Pictures/memes/nice.png"

  - trigger: ":breckfast"
    image_path: "/home/felix/Pictures/memes/breckfast.jpg"

  - trigger: ":what"
    image_path: "/home/felix/Pictures/memes/what.png"

