#!/usr/bin/env bash
# AUTOSTARTING APPLICATIONS
# this script is called in the i3 config

# touchpad gestures
libinput-gestures-setup start

# usb auto mounting
udiskie &

# red light filter
redshift &

telegram-desktop -startintray

# hide mouse cursor on inactivity
unclutter --timeout 3 --ignore-scrolling -b --jitter 1

# blueman without tray ??

# espanso daemon &

emacs --daemon

# google drive client
insync start

killall pulseaudio ; pulseaudio &

# scrolling
imwheel &
