#! /bin/sh
# BSWPWM CONFIG SCRIPT

# clear rules
bspc rule -r "*"

# start hotkey daemon
sxhkd &

# fix cursor 
xsetroot -cursor_name left_ptr &

# fix IntelliJ and other JetBrains or Java Applications
wmname LG3D

sh ~/scripts/startup &
sh ~/scripts/screen.sh &
# sh ~/scripts/modmap/modmap.sh &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2

bspc config top_padding 0
bspc config bottom_padding 0

bspc config single_monocle true
bspc config gapless_monocle false

# pywal colors are loaded in pywal_reload.sh 

bspc config focus_follows_pointer true

bspc rule -a mpv state=fullscreen

# bspc rule -a "*" state=pseudo_tiled # all windows pseudo tiling
bspc rule -a URxvt state=pseudo_tiled
bspc rule -a Pcmanfm state=pseudo_tiled
bspc rule -a TelegramDesktop state=pseudo_tiled
bspc rule -a Pavucontrol state=pseudo_tiled
bspc rule -a Insync state=pseudo_tiled
bspc rule -a Tlp-UI state=pseudo_tiled
bspc rule -a SimpleScreenRecorder state=pseudo_tiled
bspc rule -a Xfce4-power-manager-settings state=pseudo_tiled
bspc rule -a Arandr state=pseudo_tiled

