#!/bin/sh
# TODO flags

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

textype() { \
	pdflatex --output-directory="$dir" "$base" &&
    biber "$base" &&
	pdflatex --output-directory="$dir" "$base"
}

case "$file" in
	*\.tex) textype "$file" ;;
    *\.md) pandoc "$file" -f markdown -t latex -o "$base".pdf --template eisvogel --listings ;;
	*\.nim) nim compile "$file" ;;
esac

