#!/bin/bash
# this was one of my first scripts, don't hate pls.
for file in *.pdf
do
	pdfinfo "$file" | grep "Pages" | awk '{print $2}' >> /tmp/pgs
done

awk '{ sum += $1 } END { print sum }' /tmp/pgs 
rm /tmp/pgs

