#!/bin/bash

FILE="$1"
FILEPATH=dirname "$1"
FILENAME=basename "$1"

mkdir /tmp/latex/
pdflatex -output-directory /tmp/latex/ "$FILE" 

# cp /tmp/latex/"$FILENAME".pdf "$FILEPATH""$FILENAME".pdf
# TODO copy pdf into scr folder 

