#!/bin/bash

FILE="$1"
FILEPATH=$(dirname "$1")
FILEN=$(basename "$1")
FILENAME=${FILEN%.tex}

mkdir /tmp/latex/
pdflatex -output-directory /tmp/latex "$FILE" 

echo "$FILENAME"
echo "$FILEPATH"

mkdir "$FILEPATH/pdf"
cp /tmp/latex/"$FILENAME".pdf "$FILEPATH"/pdf/"$FILENAME".pdf

