#!/bin/sh

if test "$#" -lt 2; then
         echo "Not enough arguments"
         exit 1
fi

TEMPLATE="$HOME/Documents/LaTeX/md-templates/$1.md"
NEWFILE="$2.md"

if test ! -f "$TEMPLATE"; then
        echo "No template with that name"
        exit 2
fi

if test -f "$NEWFILE"; then
        echo "file already exists"
        exit 2
fi

cp "$TEMPLATE" "$NEWFILE"
nvim "$NEWFILE"

