#!/bin/bash
# TODO: check if file already exists and if template exists 

if test "$#" -lt 2; then
	echo "Not enough arguments"
	exit 1
fi

TEMPLATE="$HOME/Documents/templates/$1.tex"
NEWFILE="$HOME/Docuemnts/$2.tex"

echo $TEMPLATE
echo $NEWFILE
# cp $HOME/Documents/templates/$0.tex $HOME/Documents/$1.tex
# cd $HOME/Documents
# vim $HOME/Documents/new_note.tex
