#!/bin/sh
# set first command line argument as wallpaper using pywal.
# reload all color changes


if [ $# -eq 1 ]
  then
    echo "ther is an arg"
    wal -q -i $1
fi

# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

# BSPWM COLORS
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
        -lb "${color0}" \
        -nb "${color0}" \
        -cb "${color0}" \
        -lf "${color7}" \
        -bf "${color7}" \
        -cf "${color7}" \
        -nf "${color7}" &
}

reload_dunst

# reload spotify / spicetify theme
spicetify update
spicetify apply

# update telgram theme
# requires https://github.com/matgua/telegram-palette-gen
~/.telegram-palette-gen/telegram-palette-gen --wal

# IntelliJ Theme
# requires https://github.com/0x6C38/intellijPywal
sh ~/scripts/intellijPywal/intellijPywalGen.sh ~/.IntelliJIdea2019.3/config

