#!/bin/bash
# set first command line argument as wallpaper using pywal (wal) or reload wallpaper.
# reload all color changes

if [ $# -eq 1 ]; then
  # SET NEW WALLPAPER
  wal -q -i $1

  # reload betterlockscreen images
  betterlockscreen -u $1 -r 1920x1080 >/dev/null &
  disown

  # reload spotify / spicetify theme
  spicetify update & 
  spicetify apply -n &

  # update telgram theme
  # requires https://github.com/matgua/telegram-palette-gen
  rm ~/.cache/telegram-palette-gen/blurred_background.png ~/.cache/telegram-palette-gen/blurred_background.jpg 2>/dev/null 
  ~/.telegram-palette-gen/telegram-palette-gen --wal
  convert ~/.cache/telegram-palette-gen/background.png -blur 0x64 ~/.cache/telegram-palette-gen/blurred_background.png 2>/dev/null & # to get even more blur 
  convert ~/.cache/telegram-palette-gen/background.jpg -blur 0x64 ~/.cache/telegram-palette-gen/blurred_background.jpg 2>/dev/null & # both jpg and png

  # IntelliJ Theme
  # requires https://github.com/0x6C38/intellijPywal
  #sh ~/scripts/intellijPywal/intellijPywalGen.sh ~/.IntelliJIdea2019.3/config
else
  # RELOAD WALLPAPER
  wal -R

fi

# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

# BSPWM COLORS
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

reload_dunst() {
  pkill dunst
  dunst \
    -frame_width 0 \
    -lb "${color0}" \
    -nb "${color0}" \
    -cb "${color0}" \
    -lf "${color7}" \
    -bf "${color7}" \
    -cf "${color7}" \
    -nf "${color7}" &
}

reload_dunst
