#!/usr/bin/env bash
# AUTOSTARTING APPLICATIONS

# touchpad gestures
# libinput-gestures-setup start

# usb auto mounting
killall udiskie; udiskie &

# red light filter
killall redshift; redshift &

telegram-desktop -startintray &

# hide mouse cursor on inactivity
killall unclutter; unclutter --timeout 3 --ignore-scrolling -b --jitter 1

# espanso daemon &

# emacs --daemon &

# bluetooth manager
blueman-tray &

# network manager
killall nm-applet ; nm-applet &

# google drive client
insync start &

killall pulseaudio ; pulseaudio &

