#!/usr/bin/env bash
# AUTOSTARTING APPLICATIONS
# don't call this scripts twice in a session 
# TODO check if already ran in session 

# touchpad gestures
# libinput-gestures-setup start

# usb auto mounting
# udiskie &

# red light filter
redshift &

# atomatic screen brightness and temperature
# clight &

telegram-desktop -startintray &

# hide mouse cursor on inactivity
unclutter --timeout 5 --ignore-scrolling -b --jitter 1

# emacs --daemon &

# bluetooth manager
# blueman-tray &

# network manager
nm-applet &

# google drive client
insync start &

xfce4-power-manager &

