#!/bin/bash

player_status=$(playerctl --player=spotify status 2> /dev/null)
if [[ $? -eq 0 ]]; then
   metadata="$(playerctl --player=spotify metadata artist 2> /dev/null) - $(playerctl --player=spotify metadata title 2> /dev/null)"
fi

if [[ $player_status = "Playing" ]]; then
    echo "$metadata"
else
    echo ""
fi
