#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
   metadata="$(playerctl metadata artist) - $(playerctl metadata title)"
  # metadata="$(playerctl metadata title)"  # for browser-playerctl
fi

if [[ $player_status = "Playing" ]]; then
    echo "$metadata"
elif [[ $player_status = "Paused" ]]; then
	echo ""
else
    echo ""
fi
